services:
  fdp-backup:
    build: .
    container_name: fdp-backup
    ports:
      - "3000:8080"  #  Access log
    volumes:
      - ./backup:/app/backup
      - ./config:/app/config
      - ./crontab/fdp-cron:/etc/cron.d/fdp-cron:rw
    environment:
      LOG_SERVER_PORT: 8080
    restart: unless-stopped
