services:
  fdp-backup:
    build: .
    container_name: fdp-backup
    volumes:
      - ./backup:/app/backup
      - ./config:/app/config
    environment:
      FDP_URLS_FILE: config/fdp_urls.txt
